#!/bin/bash


/etc/init.d/pineapd start






echo "setting up pineap"
 

/usr/bin/pineap /tmp/pineap.conf  beacon_interval AGGRESSIVE

/usr/bin/pineap /tmp/pineap.conf  broadcast_pool on 

/usr/bin/pineap /tmp/pineap.conf  beacon_response_interval AGGRESSIVE

/usr/bin/pineap /tmp/pineap.conf  beacon_responses on

/usr/bin/pineap /tmp/pineap.conf  capture_ssids on

/usr/bin/pineap /tmp/pineap.conf  karma on


/usr/bin/pineap /tmp/pineap.conf  run_scan 60 0



echo "running scan for 60 seconds "

 
sleep 60

/usr/bin/pineap list_ssids > loggington.txt

/usr/bin/pineap list_probes > loggington2.txt 



echo "adding ssids"

sleep 10


/usr/bin/pineap broadcast_pool off

/usr/bin/pineap beacon_responses off

/usr/bin/pineap capture_ssids off

/usr/bin/pineap karma off

/usr/bin/pineap logging off


/usr/bin/pineap list_probes

/usr/bin/pineap get_status

/usr/bin/pineap stop_scan

/etc/init.d/pineapd stop
